#######################################################################################
# Book settings
title                         : Applied Machine Learning with Python
author                        : Nana. Boateng
logo                          : 'qe-logo-large.png'
email                         :  restanalytics148@gmail.com

# Short description about the book
description: >-
  This book presents a comprehensive machine learning topics written by Nana. Boateng


execute:
  execute_notebooks           : cache


html:
  favicon                     : 'qe-logo-large.png'
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issue_button            : true



execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url: https://github.com/nanaboateng148/Applied-Machine-Learning-with-Python
  #path_to_book: path/to/your/book  # An optional path to your book, defaults to repo root
  branch: gh-pages  # An optional branch, defaults to `master`
html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_multitoc_numbering: false
  only_build_toc_files: true 


binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
